name: learn-github-actions
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
    paths:
      - '**.js'
    paths-ignore:
      - 'doc/**'
jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      
      - name: npm test
        run: npm run test

      - name: RUn build
        run : npm run build